### ISSUE TITLE
How scalable fastlink with mln rows tables?

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [kosukeimai/fastLink#48]
I tried to search for this question but could not get any performance wise answers. Could anyone suggest whether fastlink is scalable enough for tables that exceeds mln rows. Thank you

**Comment by aalexandersson** [comment]
Currently, fastLink without blocking cannot handle tables with millions of rows. You would need [splink](https://github.com/moj-analytical-services/splink) (an independently developed version of fastLink for Apache Spark) or fastLink with blocking for such large linkages. I am not a fastLink developer but I routinely use fastLink with approximately 0.1 * 3.5 million rows which in practice require at least two blocks.

The developers are working on making fastLink faster. Hopefully, they can release a faster version in 2021.

**Comment by Ibrokhimsadikov** [comment]
Thank you, @aalexandersson  for your answer, much appreciate your opinion
