### ISSUE TITLE
aggconfusion development update

### ISSUE THREAD

**Issue by SamShin** [kosukeimai/fastLink#69]
Hi,

Thank you for writing such an amazing package. I am trying to calculate the precision and recall and so I am trying to use the confusion table. But since I want to use blocking methods, it seems like I would have to use aggconfusion to do so which is currently under development. Is there any other ways to find the precision and recall outside of manually calculating them?

Thanks in advance,
Sam

**Comment by aalexandersson** [comment]
Disclaimer: I am a regular `fastLink` user, not a `fastLink` developer.

You can use the function `confusion()` to find the precision and recall. I provided an example in [https://github.com/kosukeimai/fastLink/issues/63#issuecomment-1255559880](https://github.com/kosukeimai/fastLink/issues/63#issuecomment-1255559880).
 
Precision = Positive Predictive Value = TP / (TP + FP) = TP / Links.
Recall = Sensitivity = TP / (TP + FN) = TP / Matches.

**Comment by SamShin** [comment]
Thank you so much for the amazing example! This is exactly what I needed.
